project:
  type: website
  output-dir: _site
  resources:
    - assets/

website:
  title: "Starsim: Agent-based disease modeling"
  navbar: false
  page-footer: " "

format:
  html:
    theme: none
    page-layout: custom
    minimal: true
    section-divs: false
