project:
  type: website
  output-dir: _site

website:
  title: "Starsim: Agent-based disease modeling"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    css: 
      - assets/css/bootstrap.min.css
      - assets/css/paper-kit.css
      - assets/css/demo.css
      - assets/css/prism.css
      - assets/css/prism-lite.css
    include-in-header:
      - text: |
          <link rel="icon" type="image/png" href="./assets/img/favicon.ico">
          <link rel="apple-touch-icon" sizes="76x76" href="./assets/img/starsim-horiz.png">
          <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <meta http-equiv="X-UA-Compatible" content="ie=edge">
          <meta name="description" content="Starsim is a flexible framework for agent-based modeling of health and disease.">
          <meta property="og:site_name" content="Starsim">
          <meta property="og:title" content="Starsim: Agent-based disease modeling">
          <meta property="og:description" content="Starsim is a flexible framework for agent-based modeling of health and disease. ">
          <meta property="og:type" content="website">
          <meta property="og:url" content="https://starsim.org/">
          <meta property="og:image" content="https://starsim.org/assets/img/starsim-horiz.png">
          <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-NK4K647');</script>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300..700&display=swap" rel="stylesheet">
          <link href='https://fonts.googleapis.com/css?family=Montserrat:400,300,700|Work+Sans|Material+Icons' rel='stylesheet' type='text/css'>
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
          <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/default.min.css">
          <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js"></script>
          <script>hljs.initHighlightingOnLoad();</script>
          <script src="https://code.iconify.design/1/1.0.3/iconify.min.js"></script>
    include-before-body:
      - text: |
          <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NK4K647" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    include-after-body:
      - text: |
          <script src="./assets/js/jquery-3.2.1.min.js" type="text/javascript"></script>
          <script src="./assets/js/prism.js" type="text/javascript"></script>
          <script src="./assets/js/jquery-ui-1.12.1.custom.min.js" type="text/javascript"></script>
          <script src="./assets/js/popper.js" type="text/javascript"></script>
          <script src="./assets/js/bootstrap.min.js" type="text/javascript"></script>
          <script src="./assets/js/bootstrap-switch.min.js"></script>
          <script src="./assets/js/paper-kit.js?v=2.1.0"></script>
          <script>
          const changeNav = (entries, observer) => {
            entries.forEach((entry) => {
              if(entry.isIntersecting && entry.intersectionRatio >= 0.85) {
                document.querySelector('.active').classList.remove('active');
                const id = entry.target.getAttribute('id');
                const newLink = document.querySelector(`[href="#${id}"]`).classList.add('active');
              }
            });
          }
          const options = {
            threshold: 0.85
          }
          const observer = new IntersectionObserver(changeNav, options);
          const sections = document.querySelectorAll('section');
          sections.forEach((section) => {
            observer.observe(section);
          });
          </script>
    toc: false
    number-sections: false
    self-contained: false

execute:
  echo: true 